### ISSUE TITLE
dpscat: On Windows 7 and higher, use a SHA-256 certificate

### ISSUE THREAD

**Issue by mcuee** [mcuee/libusbk#20]
https://github.com/DarkCloud14/libusbk/commit/3e3ecfbc397b24805da13fc9f5390bf9b28fa84a
https://github.com/DarkCloud14/libusbk/commit/c943a696e2929aab98c435a11797f0ec8d0d0f3e

Newer Windows versions (especially 10) don't like when the INF is signed by a
SHA-1 certificate. They don't block the installation, but they won't use the
driver automatically, either.

**Comment by mcuee** [comment]
Original fix
https://github.com/Stevie-O/libusbk/commit/3e3ecfbc397b24805da13fc9f5390bf9b28fa84a

**Comment by TravisRo** [comment]
Patch Applied. Thanks!
