### ISSUE TITLE
How to handle the stall PID and what causes it?

### ISSUE THREAD

**Issue by only-test-linux** [mcuee/libusbk#31]
How to handle the stall PID and what causes it?

**Comment by mcuee** [comment]
Read the ABCs of USB first before you try to work with USB devices.
https://www.usbmadesimple.co.uk/

**Comment by mcuee** [comment]
This github is for technical support, but rather for issue reporting. I will close the issue.

**Comment by mcuee** [comment]
If you have generic USB related issues, please ask in relevant forum or mailing list.
