### ISSUE TITLE
libusb_alloc_streams

### ISSUE THREAD

**Issue by Ying-Pin-Wu** [mcuee/libusbk#39]
I didn't find function that allocate stream numbers like libusb on libusbK,
Does the libusbK support this funciton?

**Comment by mcuee** [comment]
That is a Linux only function as of now.

WinUSB/libusbk.sys/libusb0.sys do not support this feature, therefore it is not possible for libusbk to support this function.

Note: Microsoft has added isochronous support for WinUSB in Windows 8.1/10 but not for USB Bulk Streams for SuperSpeed USB devices.
Ref: https://techcommunity.microsoft.com/t5/microsoft-usb-blog/using-winusb-for-usb-3-0-superspeed-devices-on-windows-8/ba-p/270761
SuperSpeed bulk endpoints support a new capability called streams . The capability multiplexes logical data streams into a single bulk endpoint. Generally speaking, WinUSB does not support communication with individual streams of a SuperSpeed bulk endpoint. At this time, you can only perform transfers to the endpoint as a whole.
