### ISSUE TITLE
Bluescreen with loose HDMI connection

### ISSUE THREAD

**Issue by FrostKiwi** [mcuee/libusbk#42]
A loose HDMI connector under vibration causes an Elgato CamLink to restart due to momentary loss of HDMI signal. When this happens during streaming via libUVC + libusbK from said connection, Windows Bluescreens and reboots. 100% repeatable.

https://user-images.githubusercontent.com/60887273/204079682-6c978ec1-d10b-4b24-a84c-e1c68f8483bd.mp4

Giving attribution is hard, but I suspect libusbK being involved, so I post it here. My exact setup surrounding this bug is posted in detail here https://github.com/libuvc/libuvc/issues/245. Windows 11, Version 21H2 build 22000.1219

I have no idea how to debug on the system level with Windows. The only kernel level debugging I have ever done is with BSDs, so I don't even know where to begin. AFAIK libusbK is the first library with system level access in the chain of streaming video via libUVC. Thus I posted it here to gain some more insight. Of course, libusbK may not even be the culprit after all.

![image](https://user-images.githubusercontent.com/60887273/204079783-3c7023fb-ed85-41d8-8906-f73ff85f85ec.png)

**Comment by mcuee** [comment]
Pretty sure this is not a libusbk problem but libusb problem. And there is no solution as now since libusb still does not support hotplug under Windows.

**Comment by mcuee** [comment]
You can post the issue in libusb github along libusb debug. I will close the issue here.
