### ISSUE TITLE
About UVC Button Event

### ISSUE THREAD

**Issue by maniish** [mcuee/libusbk#44]
Hello,

I am using Camera device which has still pin button on it (Webcam/DentalCam). I want to capture the button of the USB device. Would it be possible with this library.

Kind Regards,
Manish

**Comment by mcuee** [comment]
libusbK is not the right library. You have to check with the vendor to see if they have the API for you.

**Comment by mcuee** [comment]
libusbK is more for generic USB device and not for USB camera (usually UVC device, with built-in Windows driver, or with vendor driver).
