### ISSUE TITLE
Driver installation failed on Mi 5 phone

### ISSUE THREAD

**Issue by topcoco** [mcuee/libusbk#51]
![image](https://github.com/mcuee/libusbk/assets/108533707/4c3f49cb-edb6-4ff7-8b58-d31d7487012c)

**Comment by mcuee** [comment]
You need to provide more info, like the Windows OS version you are using.

Is this using x86 or x64? 

Windows on ARM or ARM64 is not supported.

**Comment by topcoco** [comment]
> You need to provide more info, like the Windows OS version you are using.
> 
> 
> 
> Is this using x86 or x64? 
> 
> 
> 
> Windows on ARM or ARM64 is not supported.

I am using the win10 x64 system. I want to know if this is a mobile device problem or a computer problem.

**Comment by mcuee** [comment]
Please try Zadig to see if it works.
https://zadig.akeo.ie/

Or try another computer.

**Comment by topcoco** [comment]
> Please try Zadig to see if it works.

Can't

![image](https://github.com/mcuee/libusbk/assets/108533707/f4767041-7c48-4329-b7c4-64d00a57d084)

**Comment by 5tiaowu** [comment]
> Please try Zadig to see if it works.
> https://zadig.akeo.ie/

Can't![image](https://github.com/mcuee/libusbk/assets/108533707/04aaced3-85cb-4ab7-8af2-ad1a738bf775)

**Comment by mcuee** [comment]
Then you have to use another computer.

**Comment by topcoco** [comment]
> Then you have to use another computer.

Do you know what the problem is? Is it a system problem or a device problem?

**Comment by mcuee** [comment]
> Do you know what the problem is? Is it a system problem or a device problem?

Should be a system problem.

**Comment by topcoco** [comment]
> > Do you know what the problem is? Is it a system problem or a device problem?
> 
> 
> 
> Should be a system problem.
> 
> 

Isn't it all right as long as it is x86 or 64?

**Comment by mcuee** [comment]
> Isn't it all right as long as it is x86 or 64?

You may want to raise an issue in libwdi project as the error code is new to me. Please post the full Zadig debug log there. Please also link to this issue as well. Thanks.
https://github.com/pbatard/libwdi/issues

I am not so sure if your issue is related to this one.
* https://github.com/pbatard/libwdi/issues/273

**Comment by mcuee** [comment]
As this is related to libwdi, I will close this issue. We can follow up in libwdi once you raise the issue.

**Comment by mcuee** [comment]
You can still post the full Zadig debug info here.
